analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#9f9f9f'
    - '#ff0100'
    - '#ff5f00'
  brandStrength: 1
  lightness: 0.375
  rhythmicContrast: 0
  saturation: 0.3125
cta: {}
layout_spectrum: 0
name: AC-Test
opengraph: {}
purpose: []
typography_spectrum: 0.51111
