name: AC-Test
favicon: null
layout_spectrum: 0.403258103877306
typography_spectrum: 0.6375788669101894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.488282791338861
  lightness: 0.5410547535866499
  saturation: 0.6723146322183311
  rhythmicContrast: 0.12979775574058294
purpose: []
