name: AC-Test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51111
title: A test run of the AI powered - the grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#9f9f9f'
    - '#ff0100'
    - '#ff5f00'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.563063
purpose: []
