analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#9f9f9f'
    - '#ff0100'
    - '#ff5f00'
  brandStrength: 1
  lightness: 0.375
  rhythmicContrast: 0.563063
  saturation: 0.4375
cta: {}
layout_spectrum: 1
name: AC-Test
opengraph: {}
purpose: []
typography_spectrum: 0.51111
