name: AC-Test
favicon: null
layout_spectrum: 0.403258103877306
typography_spectrum: 0.6375788669101894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#9f9f9f'
    - '#ff0100'
    - '#ff5f00'
  brandStrength: 1
  lightness: 0.5410547535866499
  saturation: 0.625
  rhythmicContrast: 0.12979775574058294
purpose: []
